let catData={"categories":[
{"category":"Abweichung", "colour":"#CBD2D8",
    "description":"Zum Hervorheben von Abweichungen (+/-) von einem festen Bezugspunkt. Typischerweise ist der Bezugspunkt Null, aber es kann auch ein Ziel oder ein langfristiger Mittelwert sein. Kann auch verwendet werden, um Gefühle zu zeigen. (positiv/neutral/negativ).)",
    "example":"Handelsbilanzüberschuss/-defizit, Klimawandel"},
{"category":"Korrelation", "colour":"#CBD2D8",
    "description":"Zeigt die Beziehung zwischen zwei oder mehr Variablen an. Seien Sie sich bewusst, dass viele Leser davon ausgehen werden, dass die Beziehungen, die Sie ihnen zeigen, kausal sind (d.h. das eine verursacht das andere).)",
    "example":"Inflation und Arbeitslosigkeit, Einkommen und Lebenserwartung"},
{"category":"Rangfolge", "colour":"#CBD2D8",
	"description":"Verwenden Sie diese Option, wenn die Position eines ITEMS in einer geordneten Liste wichtiger ist als sein absoluter oder relativer Wert. Scheuen Sie sich nicht, die wichtgen Punkte hervorzuheben.",
	"example":"Reichtum, Deprivation, Ligatabellen, Wahlergebnisse der Wahlkreise"},
{"category":"Verteilung", "colour":"#CBD2D8",
    "description":"Zeigen Sie Werte in einem Datensatz und wie oft sie vorkommen. Die Form (oder „SCREW“) einer Verteilung kann eindrucksvolle Art und Weise sein, den Mangel an Einheitlichkeit oder die Ungleichheit in den Daten hervorzuheben.",
    "example":"Einkommensverteilung, Verteilung der Bevölkerung (Alter/Geschlecht)"},
{"category":"Zeitliche Veränderung", "colour":"#CBD2D8",
	"description":"Setzen Sie Akzente bei sich ändernden Trends. Dabei kann es sich um kurze (Intraday-)Bewegungen oder um ausgedehnte Serien über Jahrzehnte oder Jahrhunderte handeln: Die Wahl des richtigen Zeitraums ist wichtig, um dem Leser einen geeigneten Kontext zu bieten.",
	"example":"Aktienkursentwicklung, ökonomische Zeitreihen"},
{"category":"Teil des Ganzen", "colour":"#CBD2D8",
    "description":"Zeigen Sie, wie eine Einheit in ihre Komponentenelemente zerlegt werden kann. Wenn das Interesse des Lesers ausschließlich auf die Größe der Komponenten gerichtet ist, sollten Sie stattdessen ein Magnitude-Typ-Diagramm in Betracht ziehen.",
    "example":"Steuerbudgets, Unternehmensstrukturen,nationale Wahlergebnisse"},
{"category":"Größen- ordnung", "colour":"#CBD2D8",
"description":"Größenvergleiche anzeigen. Diese können relativ (nur in der Lage sein, größer zu sehen) oder absolut (Notwendigkeit, feine Dierenzen zu sehen) sein. In der Regel handelt es sich dabei um eine 'gezählte' Zahl (z.B. Barrel, Dollar oder Menschen) und nicht um einen berechneten Satz oder Prozentsatz.",
"example":"Rohstoffproduktion, Marktkapitalisierung"},
{"category":"Räumlich", "colour":"#CBD2D8",
"description":"Abgesehen von Locator-Karten, die nur dann verwendet werden, wenn genaue Standorte oder geographische Muster in den Daten für den Leser wichtiger sind als alles andere. ",
"example":"Bevölkerungsdichte, Standorte der natürlichen Ressourcen, Naturkatastrophen / Auswirkungen, Einzugsgebiete, Variation der Wahlergebnisse"},
{"category":"Fluss", "colour":"#CBD2D8",
"description":"Zeigen Sie dem Leser Volumen oder Intensität der Bewegung zwischen zwei oder mehr Zuständen oder Zuständen. Dies können logische Sequenzen oder geographische Orte sein.",
"example":"Bewegung von Geldern, Handel, Migranten, Klagen, Informationen; Beziehungsdiagramme."}]
}

