let catData={"categories":[
{"category":"Abwei- chung", "colour":"#CBD2D8",
    "description":"Zum Hervorheben von Abweichungen von einem festen Bezugspunkt nach oben oder unten. Typischerweise ist der Bezugspunkt Null, aber es kann auch ein Ziel oder ein langfristiger Mittelwert sein. Kann auch verwendet werden, um Haltungen wiederzugeben (positiv/neutral/negativ).",
    "example":"Handelsbilanzüberschuss/-defizit, Klimawandel, politische Umfragen"},
{"category":"Korrela- tion", "colour":"#CBD2D8",
    "description":"Zeigt die Beziehung zwischen zwei oder mehr Variablen an. Seien Sie sich bewusst, dass viele Leser davon ausgehen werden, dass die dargestellten Beziehungen kausal sind (also, dass das eine das verursacht andere).",
    "example":"Inflation und Arbeitslosigkeit, Einkommen und Lebenserwartung"},
{"category":"Rangfolge", "colour":"#CBD2D8",
	"description":"Verwenden Sie diese Option, wenn die Position eines Elements in einer geordneten Liste wichtiger ist als sein absoluter oder relativer Wert. Für die Geschichte wichtige Datenpunkte können zusätzlich hervorgehoben werden.",
	"example":"Reichtum, Deprivation, Ligatabellen, Wahlergebnisse der Wahlkreise"},
{"category":"Verteilung", "colour":"#CBD2D8",
    "description":"Zeigen Sie welche Werte wie oft in einem Datensatz vorkommen. Die Form einer Verteilung kann eindrucksvolle Art und Weise sein, den Mangel an Einheitlichkeit oder die Ungleichheit in den Daten hervorzuheben.",
    "example":"Einkommensverteilung, Verteilung der Bevölkerung (Alter/Geschlecht)"},
{"category":"Zeitliche Verän- derung", "colour":"#CBD2D8",
	"description":"Setzen Sie Akzente bei sich verändernden Trends. Dabei kann es sich um kurze (täglich wechselnde) Bewegungen handeln oder um ausgedehnte Serien über Jahrzehnte oder Jahrhunderte: Die Wahl des richtigen Zeitraums ist wichtig, um dem Leser einen geeigneten Kontext zu bieten.",
	"example":"Aktienkursentwicklung, ökonomische Zeitreihen, Exportreihen, CO2-Emissionen"},
{"category":"Teil des Ganzen", "colour":"#CBD2D8",
    "description":"Zeigen Sie, wie eine Einheit in ihre Einzelteile zerlegt werden kann. Wenn das Interesse des Lesers ausschließlich auf die Größe der Komponenten gerichtet sein soll, sollten Sie stattdessen einen anderen Diagrammtyp in Betracht ziehen.",
    "example":"Steuerbudgets, Unternehmensstrukturen, nationale Wahlergebnisse"},
{"category":"Grössen- ordnung", "colour":"#CBD2D8",
"description":"Dienen dazu die Größe verschiedener Variablen einzuordnen: Entweder relativ zu einer Gesamtgröße für mehr Kontext, oder absolut für feinere Differenzen. In der Regel handelt es sich dabei um eine 'gezählte' Zahl (z.B. Barrel, Dollar oder Menschen) und nicht um einen berechneten Satz oder Prozentsatz.",
"example":"Rohstoffproduktion, Marktkapitalisierung"},
{"category":"Räumlich", "colour":"#CBD2D8",
"description":"Während Verortungskarten für die genaue Darstellung von Standorten genutzt werden, geht es bei allen anderen Kartentypen darum, geographische Muster hervorzuheben. Zeigt sich kein geographisches Muster, ist eine andere Darstellungsform evtl. geeigneter.",
"example":"Bevölkerungsdichte, Standorte der natürlichen Ressourcen, Naturkatastrophen / Auswirkungen, Einzugsgebiete, Variation der Wahlergebnisse"},
{"category":"Fluss", "colour":"#CBD2D8",
"description":"Zeigen wie sich Volumen oder Intensität zwischen zwei oder mehr Zuständen ändert. Dies können logische Abfolgen oder geographische Orte sein.",
"example":"Bewegung von Geldern, Handel, Migranten, Wählerwanderungen"}]
}

